spring:
  application:
    name: usercrudapi

  datasource:
    url: jdbc:postgresql://localhost:5432/usercrudapi
    username: admin
    password: admin123
    driver: org.postgresql.Drive

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8180


